"""v2.0:全表/欄位 COMMENT 回填(自 SQLAlchemy model `comment=`)。

201–205 已於 18 張既有表的 model 補上欄位級 `comment=`(與 Design-Base
§ 自我說明 / § 3.5 雙軌一致要求對齊)。本檔把表級 + 欄位級 COMMENT 一次回寫
DB,讓 DBeaver / `psql \\d+` 可直接讀 schema,並使 Base.metadata 與 DB 對齊。

實作改用手寫 `op.execute("COMMENT ON ...")`(非 autogenerate):
- 本專案的 index / FK 定義於 raw-SQL baseline,未鏡射進 SQLAlchemy model,
  `--autogenerate` 會夾帶大量 `drop_index` / `create_index` / `drop_constraint`
  / `create_foreign_key` 雜訊(且重建 index 會遺失 partial `WHERE` 述詞),
  非純 comment 異動,不可採用。改以手寫純 COMMENT 語句,杜絕結構誤動。
- 欄位級文案逐字取自各 model `comment=`(201–205 就位),表級文案取自
  0021_table_catalog seed 的 display_name_zh(Design-Base § 3.5 指定同源)。
- table_catalog 不在本檔(0021 建表時已帶表級 + 欄位級 COMMENT)。
- downgrade 將本檔回寫的 COMMENT 還原為 NULL。

涵蓋 18 張既有表:ai_eval_judge_settings / ai_model_eval_candidates /
ai_model_evaluations / allowed_models / api_key_requests / audit_logs /
departments / internal_keys / model_tiers / models / openrouter_keys /
projects / refresh_tokens / sdk_api_keys / usage_logs / user_tokens /
user_tokens_revocations / users。

Revision ID: 0022_backfill_comments
Revises: 0021_table_catalog
Create Date: 2026-06-25

註:revision id 取 `0022_backfill_comments`(22 字)而非與檔名同字串,因
`alembic_version.version_num` 為 VARCHAR(32),完整檔名前綴會超長截斷;檔名
仍依 task-206 規格為 `0022_backfill_table_column_comments.py`。
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0022_backfill_comments"
down_revision: str | Sequence[str] | None = "0021_table_catalog"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("COMMENT ON TABLE ai_eval_judge_settings IS '判別模型設定'")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.ai_judge_setting_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.model_uid IS '被選為判別模型的模型(軟引用 models.model_uid) | judge model'")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.ai_judge_slot IS '判別模型槽位 1/2/3(唯一,限定恰 3 個) | judge slot 1/2/3'")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE ai_model_eval_candidates IS '模型評審候選'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_candidate_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_evaluation_uid IS '對應父表(軟引用 ai_model_evaluations.ai_evaluation_uid) | parent evaluation'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.model_uid IS '產生此候選的判別模型(軟引用 models.model_uid) | judge model'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_recommend_model IS '推薦模型(限白名單,評審產出,v2.0.1 寫入) | recommended model (judge output)'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_recommend_tier IS '推薦模型層級(由 model 反查) | recommended tier'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_recommend_reason IS '推薦理由(評審產出) | recommendation reason (judge output)'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_fit_score IS '輸出吻合度 0–1(評審產出) | fit score 0–1 (judge output)'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_self_vote IS '推薦是否與原模型同廠商(偏差監控) | self-vote flag (bias monitoring)'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE ai_model_evaluations IS '模型評審結果'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_evaluation_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.usage_log_uid IS '來源 log(軟引用 usage_logs.usage_log_uid,一對一 unique) | source usage log'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.department_uid IS '部門(denormalize 自 usage_logs;軟引用 departments.department_uid) | denormalized department'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.user_uid IS '使用者(denormalize 自 usage_logs;軟引用 users.user_uid) | denormalized user'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_original_model IS '原使用模型(= usage_logs.model) | original model'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_task_summary IS '任務工作摘要(評審產出,v2.0.1 寫入) | task summary (judge output)'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_task_intent IS '任務意圖(評審產出) | task intent (judge output)'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_task_complexity IS '任務複雜度(評審產出) | task complexity (judge output)'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.status IS '評審狀態:pending/evaluated/error | evaluation status'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_evaluated_at IS '評審完成時間(UTC+8,v2.0.1 寫入) | evaluated at'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE allowed_models IS '模型白名單'")
    op.execute("COMMENT ON COLUMN allowed_models.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN allowed_models.allowed_model_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN allowed_models.model_key IS '白名單 model_key,sync 後僅此表 is_active=TRUE 者啟用 | whitelisted model key'")
    op.execute("COMMENT ON COLUMN allowed_models.note IS '備註 | note'")
    op.execute("COMMENT ON COLUMN allowed_models.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN allowed_models.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN allowed_models.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN allowed_models.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE api_key_requests IS '金鑰申請單'")
    op.execute("COMMENT ON COLUMN api_key_requests.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN api_key_requests.request_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN api_key_requests.applicant_user_uid IS '申請人(軟引用 users.user_uid,後端由 Actor 注入) | applicant user'")
    op.execute("COMMENT ON COLUMN api_key_requests.department_name IS '申請填寫的部門名稱 | requested department name'")
    op.execute("COMMENT ON COLUMN api_key_requests.department_code IS '申請填寫的部門代碼 | requested department code'")
    op.execute("COMMENT ON COLUMN api_key_requests.project_name IS '申請的專案名稱 | requested project name'")
    op.execute("COMMENT ON COLUMN api_key_requests.project_url IS '專案連結(須為 GitHub / Replit,驗證於 schema) | project URL'")
    op.execute("COMMENT ON COLUMN api_key_requests.owner_name IS '專案負責人姓名(PII) | owner name (PII)'")
    op.execute("COMMENT ON COLUMN api_key_requests.owner_email IS '專案負責人 Email(PII) | owner email (PII)'")
    op.execute("COMMENT ON COLUMN api_key_requests.status IS '申請狀態:manual_pending/agent_done/done/revoked/cancelled | request status'")
    op.execute("COMMENT ON COLUMN api_key_requests.cancel_reason IS '取消原因 | cancel reason'")
    op.execute("COMMENT ON COLUMN api_key_requests.cancel_source IS '取消來源(user / admin 等) | cancel source'")
    op.execute("COMMENT ON COLUMN api_key_requests.handled_by_user_uid IS '人工處理的 admin(軟引用 users.user_uid) | handled-by admin'")
    op.execute("COMMENT ON COLUMN api_key_requests.agent_decision IS 'AI 欄位驗證決策 {confidence, reason} | AI field-validation decision'")
    op.execute("COMMENT ON COLUMN api_key_requests.error_message IS 'AI / 開通失敗原因 | AI or provisioning error message'")
    op.execute("COMMENT ON COLUMN api_key_requests.created_project_uid IS '開通建立的專案(軟引用 projects.project_uid) | created project'")
    op.execute("COMMENT ON COLUMN api_key_requests.created_user_uid IS '開通建立的使用者(軟引用 users.user_uid) | created user'")
    op.execute("COMMENT ON COLUMN api_key_requests.created_sdk_key_uid IS '開通建立的 SDK 金鑰(軟引用 sdk_api_keys.sdk_api_key_uid) | created SDK key'")
    op.execute("COMMENT ON COLUMN api_key_requests.matched_department_uid IS '比對到的既有部門(軟引用 departments.department_uid) | matched department'")
    op.execute("COMMENT ON COLUMN api_key_requests.provisioned_secrets IS '一次性開通憑證 {sdk_key, user_token, project_code},領取後清空(機密) | one-time provisioned secrets (cleared after pickup)'")
    op.execute("COMMENT ON COLUMN api_key_requests.processed_at IS '進入終態時間(UTC+8) | processed at'")
    op.execute("COMMENT ON COLUMN api_key_requests.notified_at IS '開通完成 Email 通知寄送成功時間(UTC+8) | notified at'")
    op.execute("COMMENT ON COLUMN api_key_requests.notify_error IS '通知信寄送失敗原因(不含憑證) | notify error message'")
    op.execute("COMMENT ON COLUMN api_key_requests.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN api_key_requests.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN api_key_requests.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN api_key_requests.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE audit_logs IS '稽核紀錄'")
    op.execute("COMMENT ON COLUMN audit_logs.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN audit_logs.audit_log_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN audit_logs.actor_user_uid IS '操作者 user_uid | actor user UID'")
    op.execute("COMMENT ON COLUMN audit_logs.actor_role IS '操作者角色 | actor role'")
    op.execute("COMMENT ON COLUMN audit_logs.action IS '操作動作 | action'")
    op.execute("COMMENT ON COLUMN audit_logs.target_type IS '操作對象類型 | target entity type'")
    op.execute("COMMENT ON COLUMN audit_logs.target_uid IS '操作對象 UID;NULL = 無特定對象 | target UID'")
    op.execute("COMMENT ON COLUMN audit_logs.result IS '操作結果(success/failure) | action result'")
    op.execute("COMMENT ON COLUMN audit_logs.detail IS '操作明細描述 | detail description'")
    op.execute("COMMENT ON COLUMN audit_logs.ip IS '操作來源 IP | source IP'")
    op.execute("COMMENT ON COLUMN audit_logs.extra IS '額外結構化資料 | extra structured data'")
    op.execute("COMMENT ON COLUMN audit_logs.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN audit_logs.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN audit_logs.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN audit_logs.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE departments IS '部門'")
    op.execute("COMMENT ON COLUMN departments.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN departments.department_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN departments.code IS '成本中心代碼 | cost center code'")
    op.execute("COMMENT ON COLUMN departments.org_code IS '組織代碼 | organization code'")
    op.execute("COMMENT ON COLUMN departments.name IS '部門名稱 | department name'")
    op.execute("COMMENT ON COLUMN departments.description IS '部門說明 | description'")
    op.execute("COMMENT ON COLUMN departments.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN departments.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN departments.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN departments.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE internal_keys IS '內部金鑰'")
    op.execute("COMMENT ON COLUMN internal_keys.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN internal_keys.internal_key_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN internal_keys.name IS '連線設定顯示名稱(管理用,非機密) | display name'")
    op.execute("COMMENT ON COLUMN internal_keys.base_url IS '內部 OpenAI-compatible LLM server base URL | internal LLM server base URL'")
    op.execute("COMMENT ON COLUMN internal_keys.key_ciphertext IS '內網 API Key 密文(AES-256-GCM;內網信任時為 NULL) | encrypted API key ciphertext (nullable)'")
    op.execute("COMMENT ON COLUMN internal_keys.key_last4 IS '金鑰末四碼(供顯示遮罩,非完整明文) | last 4 chars for masked display'")
    op.execute("COMMENT ON COLUMN internal_keys.rpm_limit IS '每分鐘請求上限(per-Key;0=不限) | requests-per-minute limit'")
    op.execute("COMMENT ON COLUMN internal_keys.min_request_interval_ms IS '最小請求間隔毫秒(per-Key;0=不限) | min request interval (ms)'")
    op.execute("COMMENT ON COLUMN internal_keys.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN internal_keys.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN internal_keys.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN internal_keys.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE model_tiers IS '模型分級'")
    op.execute("COMMENT ON COLUMN model_tiers.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN model_tiers.tier_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN model_tiers.key IS '分級 key,一旦建立不可改名(避免 models.tier_key 失聯) | tier key (immutable)'")
    op.execute("COMMENT ON COLUMN model_tiers.label_zh IS '中文顯示名 | Chinese label'")
    op.execute("COMMENT ON COLUMN model_tiers.label_en IS '英文顯示名 | English label'")
    op.execute("COMMENT ON COLUMN model_tiers.color IS '顯示色碼 | display color'")
    op.execute("COMMENT ON COLUMN model_tiers.sort_order IS '排序順序 | sort order'")
    op.execute("COMMENT ON COLUMN model_tiers.auto_match_min_price_per_mtok IS '同步時自動匹配的價格下限(USD per token);NULL = 不參與自動匹配 | auto-match min price'")
    op.execute("COMMENT ON COLUMN model_tiers.auto_match_max_price_per_mtok IS '同步時自動匹配的價格上限(USD per token);NULL = 不參與自動匹配 | auto-match max price'")
    op.execute("COMMENT ON COLUMN model_tiers.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN model_tiers.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN model_tiers.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN model_tiers.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE models IS '模型'")
    op.execute("COMMENT ON COLUMN models.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN models.model_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN models.provider IS '模型 provider:openrouter(由同步寫入)/ internal(admin 手動建立) | model provider source'")
    op.execute("COMMENT ON COLUMN models.model_key IS '模型對外識別 key:openrouter 為 openai/gpt-4o,internal 為 admin 自訂 | external model key'")
    op.execute("COMMENT ON COLUMN models.name IS '模型顯示名稱 | model display name'")
    op.execute("COMMENT ON COLUMN models.description IS '模型描述 | model description'")
    op.execute("COMMENT ON COLUMN models.context_length IS '上下文長度(token 數) | context length in tokens'")
    op.execute("COMMENT ON COLUMN models.max_completion_tokens IS '單次回應最大 token 數 | max completion tokens'")
    op.execute("COMMENT ON COLUMN models.modality IS '模態描述字串(OpenRouter architecture.modality) | modality string'")
    op.execute("COMMENT ON COLUMN models.input_modalities IS '可接受之輸入模態 tag(如 text/image/file);OpenRouter 由 sync 覆寫,internal 可由 admin 自訂 | input modalities'")
    op.execute("COMMENT ON COLUMN models.output_modalities IS '可產出之輸出模態 tag(如 text);OpenRouter 由 sync 覆寫,internal 可由 admin 自訂 | output modalities'")
    op.execute("COMMENT ON COLUMN models.tokenizer IS '分詞器類型 | tokenizer type'")
    op.execute("COMMENT ON COLUMN models.price_prompt_per_token IS 'prompt 每 token 單價(USD) | prompt price per token (USD)'")
    op.execute("COMMENT ON COLUMN models.price_completion_per_token IS 'completion 每 token 單價(USD) | completion price per token (USD)'")
    op.execute("COMMENT ON COLUMN models.price_image_per_image IS '每張圖片單價(USD) | image price per image (USD)'")
    op.execute("COMMENT ON COLUMN models.price_request_flat IS '每次請求固定費用(USD) | flat price per request (USD)'")
    op.execute("COMMENT ON COLUMN models.is_moderated IS '平台控管(可由 admin 編輯) | moderated flag (admin editable)'")
    op.execute("COMMENT ON COLUMN models.tier_key IS 'model_tiers.key 的軟引用;NULL = 未分級 | tier key soft-reference (NULL = unranked)'")
    op.execute("COMMENT ON COLUMN models.openrouter_created_at IS 'OpenRouter 端模型建立時間 | OpenRouter-side created at'")
    op.execute("COMMENT ON COLUMN models.last_synced_at IS '最近一次同步時間 | last synced at'")
    op.execute("COMMENT ON COLUMN models.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN models.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN models.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN models.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE openrouter_keys IS 'OpenRouter 金鑰'")
    op.execute("COMMENT ON COLUMN openrouter_keys.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN openrouter_keys.openrouter_key_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN openrouter_keys.department_uid IS '所屬部門(軟引用 departments.department_uid) | owning department'")
    op.execute("COMMENT ON COLUMN openrouter_keys.name IS '金鑰顯示名稱(管理用,非機密) | key display name'")
    op.execute("COMMENT ON COLUMN openrouter_keys.key_ciphertext IS 'OpenRouter API Key 密文(AES-256-GCM 加密,金鑰由 ENCRYPTION_KEY 注入) | encrypted API key ciphertext'")
    op.execute("COMMENT ON COLUMN openrouter_keys.key_prefix IS '金鑰前綴(供顯示遮罩,非完整明文) | key prefix for masked display'")
    op.execute("COMMENT ON COLUMN openrouter_keys.key_last4 IS '金鑰末四碼(供顯示遮罩,非完整明文) | last 4 chars for masked display'")
    op.execute("COMMENT ON COLUMN openrouter_keys.credits_used_usd IS 'OpenRouter 帳號已用額度(USD,sync 回填,僅 admin 可見) | credits used (USD)'")
    op.execute("COMMENT ON COLUMN openrouter_keys.credits_limit_usd IS 'OpenRouter 帳號額度上限(USD,sync 回填;NULL=無上限) | credits limit (USD)'")
    op.execute("COMMENT ON COLUMN openrouter_keys.credits_is_free_tier IS '是否為免費方案帳號(sync 回填) | free tier flag'")
    op.execute("COMMENT ON COLUMN openrouter_keys.credits_synced_at IS '餘額最後同步時間(UTC+8) | credits last synced at'")
    op.execute("COMMENT ON COLUMN openrouter_keys.rpm_limit IS '每分鐘請求上限(per-Key;0=不限) | requests-per-minute limit'")
    op.execute("COMMENT ON COLUMN openrouter_keys.min_request_interval_ms IS '最小請求間隔毫秒(per-Key;0=不限) | min request interval (ms)'")
    op.execute("COMMENT ON COLUMN openrouter_keys.disabled_until IS '短期停用截止時間,撞 401/402 時設 now()+cooldown,到期自動恢復(UTC+8) | disabled until'")
    op.execute("COMMENT ON COLUMN openrouter_keys.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN openrouter_keys.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN openrouter_keys.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN openrouter_keys.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE projects IS '專案'")
    op.execute("COMMENT ON COLUMN projects.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN projects.project_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN projects.department_uid IS '所屬部門 UID(關聯 departments) | department UID'")
    op.execute("COMMENT ON COLUMN projects.code IS '專案代碼(Snowflake,呼叫端 X-Project-Code) | project code'")
    op.execute("COMMENT ON COLUMN projects.name IS '專案名稱 | project name'")
    op.execute("COMMENT ON COLUMN projects.description IS '專案說明 | description'")
    op.execute("COMMENT ON COLUMN projects.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN projects.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN projects.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN projects.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE refresh_tokens IS '更新權杖'")
    op.execute("COMMENT ON COLUMN refresh_tokens.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN refresh_tokens.refresh_token_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN refresh_tokens.user_uid IS '所屬使用者 UID(關聯 users) | user UID'")
    op.execute("COMMENT ON COLUMN refresh_tokens.family_uid IS 'token 家族 UID(rotation 鏈,偵測重放) | token family UID'")
    op.execute("COMMENT ON COLUMN refresh_tokens.token_hash IS 'refresh token 雜湊 | token hash'")
    op.execute("COMMENT ON COLUMN refresh_tokens.issued_at IS '簽發時間 | issued at'")
    op.execute("COMMENT ON COLUMN refresh_tokens.expires_at IS '到期時間 | expires at'")
    op.execute("COMMENT ON COLUMN refresh_tokens.revoked_at IS '撤銷時間 | revoked at'")
    op.execute("COMMENT ON COLUMN refresh_tokens.replaced_by_uid IS '被哪張新 token 取代(rotation) | replaced-by token UID'")
    op.execute("COMMENT ON COLUMN refresh_tokens.user_agent IS '簽發時的 User-Agent | user agent'")
    op.execute("COMMENT ON COLUMN refresh_tokens.ip IS '簽發時的來源 IP | source IP'")
    op.execute("COMMENT ON COLUMN refresh_tokens.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN refresh_tokens.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN refresh_tokens.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN refresh_tokens.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE sdk_api_keys IS 'SDK API 金鑰'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.sdk_api_key_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.department_uid IS '所屬部門(軟引用 departments.department_uid) | owning department'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.name IS '金鑰顯示名稱(管理用,非機密) | key display name'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.key_hash IS '金鑰驗證雜湊(argon2id,不可逆) | key verification hash (argon2id)'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.key_prefix IS '金鑰前綴(供顯示遮罩與查找,非完整明文) | key prefix for masked display'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.key_values IS '完整金鑰明文,供後台直編填值(業務取捨,未加密;舊資料 NULL=請重建) | full key plaintext (unencrypted, business trade-off)'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN sdk_api_keys.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE usage_logs IS '用量紀錄'")
    op.execute("COMMENT ON COLUMN usage_logs.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN usage_logs.usage_log_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN usage_logs.user_uid IS '呼叫者 user_uid | caller user UID'")
    op.execute("COMMENT ON COLUMN usage_logs.department_uid IS '呼叫者所屬部門 UID | caller department UID'")
    op.execute("COMMENT ON COLUMN usage_logs.project_uid IS 'v1.5 加入;允許 NULL 以容錯既有歷史紀錄(代理新呼叫一律必帶 X-Project-Code) | project UID'")
    op.execute("COMMENT ON COLUMN usage_logs.openrouter_key_uid IS '本次呼叫使用的 OpenRouter 金鑰 UID | OpenRouter key UID'")
    op.execute("COMMENT ON COLUMN usage_logs.model IS '呼叫的模型 key | model key'")
    op.execute("COMMENT ON COLUMN usage_logs.model_uid IS 'v1.1 加入;允許 NULL 容錯既有歷史與白名單拒絕情境 | model UID'")
    op.execute("COMMENT ON COLUMN usage_logs.prompt_tokens IS 'prompt token 數 | prompt tokens'")
    op.execute("COMMENT ON COLUMN usage_logs.completion_tokens IS 'completion token 數 | completion tokens'")
    op.execute("COMMENT ON COLUMN usage_logs.total_tokens IS '總 token 數 | total tokens'")
    op.execute("COMMENT ON COLUMN usage_logs.cost_usd IS '本次呼叫成本(USD) | cost in USD'")
    op.execute("COMMENT ON COLUMN usage_logs.latency_ms IS '延遲(毫秒) | latency in ms'")
    op.execute("COMMENT ON COLUMN usage_logs.status IS '呼叫狀態 | call status'")
    op.execute("COMMENT ON COLUMN usage_logs.error_code IS '錯誤碼;NULL = 無錯誤 | error code'")
    op.execute("COMMENT ON COLUMN usage_logs.request_content IS '請求內容 | request content'")
    op.execute("COMMENT ON COLUMN usage_logs.response_summary IS '回應摘要 | response summary'")
    op.execute("COMMENT ON COLUMN usage_logs.openrouter_generation_id IS 'OpenRouter 生成 ID | OpenRouter generation ID'")
    op.execute("COMMENT ON COLUMN usage_logs.used_tools IS 'v1.6.2 加入;本次呼叫是否帶 tools(如 web search),tools 可能觸發額外計費,標記供後台篩選與計費分析 | used tools flag'")
    op.execute("COMMENT ON COLUMN usage_logs.ai_evaluated_at IS 'v2.0 加入;最新一次評審執行時間(全棧 UTC+8),NULL=尚未評審;不論成敗皆由評審寫入端更新;排程器以 IS NULL 掃出待評審筆 | AI evaluated at'")
    op.execute("COMMENT ON COLUMN usage_logs.ai_evaluated_status IS 'v2.0 加入;最新一次評審結果:NULL=尚未評審、0=失敗、1=成功 | AI evaluated status'")
    op.execute("COMMENT ON COLUMN usage_logs.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN usage_logs.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN usage_logs.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN usage_logs.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE user_tokens IS '使用者權杖'")
    op.execute("COMMENT ON COLUMN user_tokens.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN user_tokens.user_tokens_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN user_tokens.user_uid IS '所屬使用者 UID(關聯 users) | user UID'")
    op.execute("COMMENT ON COLUMN user_tokens.token IS 'User Token 明文,供重複申請沿用與追蹤 | user token value'")
    op.execute("COMMENT ON COLUMN user_tokens.issued_at IS '簽發時間 | issued at'")
    op.execute("COMMENT ON COLUMN user_tokens.revoked_at IS '撤銷時間(標記停用) | revoked at'")
    op.execute("COMMENT ON COLUMN user_tokens.revoked_reason IS '撤銷原因 | revoked reason'")
    op.execute("COMMENT ON COLUMN user_tokens.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN user_tokens.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN user_tokens.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN user_tokens.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE user_tokens_revocations IS '使用者權杖撤銷'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.user_tokens_revocation_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.user_uid IS '所屬使用者 UID(關聯 users) | user UID'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.revoked_issued_at IS '被撤銷 token 的簽發時間(浮水印門檻,早於此一律失效) | revoked token issued-at watermark'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.revoked_at IS '撤銷時間 | revoked at'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.reason IS '撤銷原因 | revoked reason'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")

    op.execute("COMMENT ON TABLE users IS '使用者'")
    op.execute("COMMENT ON COLUMN users.pid IS '內部自增主鍵,禁對外暴露 | internal auto-increment PK'")
    op.execute("COMMENT ON COLUMN users.user_uid IS '對外 UUID 識別(UUIDv7) | external UID'")
    op.execute("COMMENT ON COLUMN users.account IS '登入帳號 | login account'")
    op.execute("COMMENT ON COLUMN users.username IS '使用者顯示名稱 | display name'")
    op.execute("COMMENT ON COLUMN users.password_hash IS '密碼雜湊(argon2id) | password hash'")
    op.execute("COMMENT ON COLUMN users.role IS '角色權限 | role'")
    op.execute("COMMENT ON COLUMN users.department_uid IS '所屬部門 UID(關聯 departments) | department UID'")
    op.execute("COMMENT ON COLUMN users.employee_id IS '員工編號 | employee ID'")
    op.execute("COMMENT ON COLUMN users.email IS '電子郵件 | email'")
    op.execute("COMMENT ON COLUMN users.sso_user_id IS 'DF-SSO 的 userId(azure oid),供 back-channel logout 反查本地帳號 | DF-SSO user ID'")
    op.execute("COMMENT ON COLUMN users.failed_login_count IS '登入失敗次數 | failed login count'")
    op.execute("COMMENT ON COLUMN users.locked_until IS '帳號鎖定至此時間 | locked until'")
    op.execute("COMMENT ON COLUMN users.password_changed_at IS '密碼最後變更時間 | password changed at'")
    op.execute("COMMENT ON COLUMN users.is_active IS '是否啟用,停用後保留資料但不可使用 | active flag'")
    op.execute("COMMENT ON COLUMN users.is_deleted IS '軟刪除標記,查詢預設過濾 is_deleted=FALSE | soft-delete flag'")
    op.execute("COMMENT ON COLUMN users.created_at IS '建立時間(UTC+8) | created at'")
    op.execute("COMMENT ON COLUMN users.updated_at IS '更新時間(UTC+8,由 trigger 維護) | updated at'")


def downgrade() -> None:
    op.execute("COMMENT ON TABLE ai_eval_judge_settings IS NULL")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.pid IS NULL")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.ai_judge_setting_uid IS NULL")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.model_uid IS NULL")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.ai_judge_slot IS NULL")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.is_active IS NULL")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.created_at IS NULL")
    op.execute("COMMENT ON COLUMN ai_eval_judge_settings.updated_at IS NULL")

    op.execute("COMMENT ON TABLE ai_model_eval_candidates IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.pid IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_candidate_uid IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_evaluation_uid IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.model_uid IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_recommend_model IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_recommend_tier IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_recommend_reason IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_fit_score IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.ai_self_vote IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.is_active IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.created_at IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_eval_candidates.updated_at IS NULL")

    op.execute("COMMENT ON TABLE ai_model_evaluations IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.pid IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_evaluation_uid IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.usage_log_uid IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.department_uid IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.user_uid IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_original_model IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_task_summary IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_task_intent IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_task_complexity IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.status IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.ai_evaluated_at IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.is_active IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.created_at IS NULL")
    op.execute("COMMENT ON COLUMN ai_model_evaluations.updated_at IS NULL")

    op.execute("COMMENT ON TABLE allowed_models IS NULL")
    op.execute("COMMENT ON COLUMN allowed_models.pid IS NULL")
    op.execute("COMMENT ON COLUMN allowed_models.allowed_model_uid IS NULL")
    op.execute("COMMENT ON COLUMN allowed_models.model_key IS NULL")
    op.execute("COMMENT ON COLUMN allowed_models.note IS NULL")
    op.execute("COMMENT ON COLUMN allowed_models.is_active IS NULL")
    op.execute("COMMENT ON COLUMN allowed_models.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN allowed_models.created_at IS NULL")
    op.execute("COMMENT ON COLUMN allowed_models.updated_at IS NULL")

    op.execute("COMMENT ON TABLE api_key_requests IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.pid IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.request_uid IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.applicant_user_uid IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.department_name IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.department_code IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.project_name IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.project_url IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.owner_name IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.owner_email IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.status IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.cancel_reason IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.cancel_source IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.handled_by_user_uid IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.agent_decision IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.error_message IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.created_project_uid IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.created_user_uid IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.created_sdk_key_uid IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.matched_department_uid IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.provisioned_secrets IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.processed_at IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.notified_at IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.notify_error IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.is_active IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.created_at IS NULL")
    op.execute("COMMENT ON COLUMN api_key_requests.updated_at IS NULL")

    op.execute("COMMENT ON TABLE audit_logs IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.pid IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.audit_log_uid IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.actor_user_uid IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.actor_role IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.action IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.target_type IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.target_uid IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.result IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.detail IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.ip IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.extra IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.is_active IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.created_at IS NULL")
    op.execute("COMMENT ON COLUMN audit_logs.updated_at IS NULL")

    op.execute("COMMENT ON TABLE departments IS NULL")
    op.execute("COMMENT ON COLUMN departments.pid IS NULL")
    op.execute("COMMENT ON COLUMN departments.department_uid IS NULL")
    op.execute("COMMENT ON COLUMN departments.code IS NULL")
    op.execute("COMMENT ON COLUMN departments.org_code IS NULL")
    op.execute("COMMENT ON COLUMN departments.name IS NULL")
    op.execute("COMMENT ON COLUMN departments.description IS NULL")
    op.execute("COMMENT ON COLUMN departments.is_active IS NULL")
    op.execute("COMMENT ON COLUMN departments.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN departments.created_at IS NULL")
    op.execute("COMMENT ON COLUMN departments.updated_at IS NULL")

    op.execute("COMMENT ON TABLE internal_keys IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.pid IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.internal_key_uid IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.name IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.base_url IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.key_ciphertext IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.key_last4 IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.rpm_limit IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.min_request_interval_ms IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.is_active IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.created_at IS NULL")
    op.execute("COMMENT ON COLUMN internal_keys.updated_at IS NULL")

    op.execute("COMMENT ON TABLE model_tiers IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.pid IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.tier_uid IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.key IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.label_zh IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.label_en IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.color IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.sort_order IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.auto_match_min_price_per_mtok IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.auto_match_max_price_per_mtok IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.is_active IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.created_at IS NULL")
    op.execute("COMMENT ON COLUMN model_tiers.updated_at IS NULL")

    op.execute("COMMENT ON TABLE models IS NULL")
    op.execute("COMMENT ON COLUMN models.pid IS NULL")
    op.execute("COMMENT ON COLUMN models.model_uid IS NULL")
    op.execute("COMMENT ON COLUMN models.provider IS NULL")
    op.execute("COMMENT ON COLUMN models.model_key IS NULL")
    op.execute("COMMENT ON COLUMN models.name IS NULL")
    op.execute("COMMENT ON COLUMN models.description IS NULL")
    op.execute("COMMENT ON COLUMN models.context_length IS NULL")
    op.execute("COMMENT ON COLUMN models.max_completion_tokens IS NULL")
    op.execute("COMMENT ON COLUMN models.modality IS NULL")
    op.execute("COMMENT ON COLUMN models.input_modalities IS NULL")
    op.execute("COMMENT ON COLUMN models.output_modalities IS NULL")
    op.execute("COMMENT ON COLUMN models.tokenizer IS NULL")
    op.execute("COMMENT ON COLUMN models.price_prompt_per_token IS NULL")
    op.execute("COMMENT ON COLUMN models.price_completion_per_token IS NULL")
    op.execute("COMMENT ON COLUMN models.price_image_per_image IS NULL")
    op.execute("COMMENT ON COLUMN models.price_request_flat IS NULL")
    op.execute("COMMENT ON COLUMN models.is_moderated IS NULL")
    op.execute("COMMENT ON COLUMN models.tier_key IS NULL")
    op.execute("COMMENT ON COLUMN models.openrouter_created_at IS NULL")
    op.execute("COMMENT ON COLUMN models.last_synced_at IS NULL")
    op.execute("COMMENT ON COLUMN models.is_active IS NULL")
    op.execute("COMMENT ON COLUMN models.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN models.created_at IS NULL")
    op.execute("COMMENT ON COLUMN models.updated_at IS NULL")

    op.execute("COMMENT ON TABLE openrouter_keys IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.pid IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.openrouter_key_uid IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.department_uid IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.name IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.key_ciphertext IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.key_prefix IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.key_last4 IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.credits_used_usd IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.credits_limit_usd IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.credits_is_free_tier IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.credits_synced_at IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.rpm_limit IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.min_request_interval_ms IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.disabled_until IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.is_active IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.created_at IS NULL")
    op.execute("COMMENT ON COLUMN openrouter_keys.updated_at IS NULL")

    op.execute("COMMENT ON TABLE projects IS NULL")
    op.execute("COMMENT ON COLUMN projects.pid IS NULL")
    op.execute("COMMENT ON COLUMN projects.project_uid IS NULL")
    op.execute("COMMENT ON COLUMN projects.department_uid IS NULL")
    op.execute("COMMENT ON COLUMN projects.code IS NULL")
    op.execute("COMMENT ON COLUMN projects.name IS NULL")
    op.execute("COMMENT ON COLUMN projects.description IS NULL")
    op.execute("COMMENT ON COLUMN projects.is_active IS NULL")
    op.execute("COMMENT ON COLUMN projects.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN projects.created_at IS NULL")
    op.execute("COMMENT ON COLUMN projects.updated_at IS NULL")

    op.execute("COMMENT ON TABLE refresh_tokens IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.pid IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.refresh_token_uid IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.user_uid IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.family_uid IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.token_hash IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.issued_at IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.expires_at IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.revoked_at IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.replaced_by_uid IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.user_agent IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.ip IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.is_active IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.created_at IS NULL")
    op.execute("COMMENT ON COLUMN refresh_tokens.updated_at IS NULL")

    op.execute("COMMENT ON TABLE sdk_api_keys IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.pid IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.sdk_api_key_uid IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.department_uid IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.name IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.key_hash IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.key_prefix IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.key_values IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.is_active IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.created_at IS NULL")
    op.execute("COMMENT ON COLUMN sdk_api_keys.updated_at IS NULL")

    op.execute("COMMENT ON TABLE usage_logs IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.pid IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.usage_log_uid IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.user_uid IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.department_uid IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.project_uid IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.openrouter_key_uid IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.model IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.model_uid IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.prompt_tokens IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.completion_tokens IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.total_tokens IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.cost_usd IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.latency_ms IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.status IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.error_code IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.request_content IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.response_summary IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.openrouter_generation_id IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.used_tools IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.ai_evaluated_at IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.ai_evaluated_status IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.is_active IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.created_at IS NULL")
    op.execute("COMMENT ON COLUMN usage_logs.updated_at IS NULL")

    op.execute("COMMENT ON TABLE user_tokens IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.pid IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.user_tokens_uid IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.user_uid IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.token IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.issued_at IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.revoked_at IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.revoked_reason IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.is_active IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.created_at IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens.updated_at IS NULL")

    op.execute("COMMENT ON TABLE user_tokens_revocations IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.pid IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.user_tokens_revocation_uid IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.user_uid IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.revoked_issued_at IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.revoked_at IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.reason IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.is_active IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.created_at IS NULL")
    op.execute("COMMENT ON COLUMN user_tokens_revocations.updated_at IS NULL")

    op.execute("COMMENT ON TABLE users IS NULL")
    op.execute("COMMENT ON COLUMN users.pid IS NULL")
    op.execute("COMMENT ON COLUMN users.user_uid IS NULL")
    op.execute("COMMENT ON COLUMN users.account IS NULL")
    op.execute("COMMENT ON COLUMN users.username IS NULL")
    op.execute("COMMENT ON COLUMN users.password_hash IS NULL")
    op.execute("COMMENT ON COLUMN users.role IS NULL")
    op.execute("COMMENT ON COLUMN users.department_uid IS NULL")
    op.execute("COMMENT ON COLUMN users.employee_id IS NULL")
    op.execute("COMMENT ON COLUMN users.email IS NULL")
    op.execute("COMMENT ON COLUMN users.sso_user_id IS NULL")
    op.execute("COMMENT ON COLUMN users.failed_login_count IS NULL")
    op.execute("COMMENT ON COLUMN users.locked_until IS NULL")
    op.execute("COMMENT ON COLUMN users.password_changed_at IS NULL")
    op.execute("COMMENT ON COLUMN users.is_active IS NULL")
    op.execute("COMMENT ON COLUMN users.is_deleted IS NULL")
    op.execute("COMMENT ON COLUMN users.created_at IS NULL")
    op.execute("COMMENT ON COLUMN users.updated_at IS NULL")
